### ISSUE TITLE
listsubscribe

### ISSUE THREAD

**Issue by kwalkerk** [mailchimp/ChimpKit2#6]
Sorry if this is not the correct place to post questions.

I'm trying to use ChimpKit in my iOS app.  Everything works fine if I 
follow the example.  However for my actual list, first name and last 
name are fields I wish to collect. 
The listsubscribe syntax in the CKList class is as follows: 
[self get:@"/" method:@"listSubscribe" id:listId merge_vars:@"" 
email_address:email send_welcome:welcome double_optin:optIn]; 
I've had no luck in formatting a string to contain the fname and lname 
values for the merge_vars variable.  I can modify the class to know 
about those variables, but I need an example of as string that would 
work for that variable so I can go forward.

**Comment by amro** [comment]
Please check out ChimpKit2
