### ISSUE TITLE
Retina support, localization support, proper protocol for delegate

### ISSUE THREAD

**Issue by gcamp** [mailchimp/ChimpKit2#7]
Just heard about this on a 5by5 podcast. I don't understand that you are advertising a framework like that, it look outdated.
- This is not retina compatible
- Images, even @1x, are not good : button is blurry and the "x" is not centered
- There is text on images : that's really bad for localization, and looks really bad on the retina display. See : http://cocoawithlove.com/2011/04/user-interface-strings-in-cocoa.html
- It would be nice to have a proper protocol for the delegate

**Comment by amro** [comment]
ChimpKit is deprecated. Please try http://github.com/mailchimp/chimpkit2 instead. The dialog included with ChimpKit2 (just checked in today) is a subclass of UIAlertView. Sorry that wasn't clear in the podcast.

**Comment by gcamp** [comment]
Thanks for the heads up amro, 

You should change the description with a link to the new framework, because a "ChimpKit" search on Google still links to this page. Sorry for the angry message earlier, the new frameworks looks a lot better!

**Comment by amro** [comment]
Yep, I updated the README -- I'll update the description as well. Definitely not an issue. ChimpKit 2 works fine but it's still in development. I'm toying with moving to blocks. It still needs a proper delegate protocol if I don't do that, though.
